name: Build and Deploy to Azure Container App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CONTAINER_REGISTRY_NAME: ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}
  AZURE_CONTAINER_APP_NAME: "prod-ca-container-deployment-mi"
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_CR_IMAGE_NAME: ${{ secrets.AZURE_CR_IMAGE_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure login using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name $AZURE_CONTAINER_REGISTRY_NAME

      - name: Build and push image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $AZURE_CONTAINER_REGISTRY_NAME.azurecr.io/$AZURE_CR_IMAGE_NAME:$IMAGE_TAG ./container-azure-deployment-api-mi
          docker push $AZURE_CONTAINER_REGISTRY_NAME.azurecr.io/$AZURE_CR_IMAGE_NAME:$IMAGE_TAG

      - name: Deploy to Container App
        run: |
          az containerapp update \
            --name $AZURE_CONTAINER_APP_NAME \
            --resource-group $AZURE_RESOURCE_GROUP \
            --image $AZURE_CONTAINER_REGISTRY_NAME.azurecr.io/$AZURE_CR_IMAGE_NAME:${{ github.sha }}

